version: '3.7'
services:
  mysql:
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nette
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - nette
    ports:
      - "3306:3306"

  php:
    platform: linux/x86_64
    build: ./.docker/php
    ports: ['9001:9000']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www']
    networks:
      - nette

  nginx:
    build: ./.docker/nginx
    ports: ['80:80']
    volumes: ['${CI_PROJECT_DIR:-.}:/var/www']
    networks:
      - nette

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - nette

networks:
  nette:
