version: '3.7'
services:
  mysql:
    image: mysql:8-debian
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nette
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    networks:
      - nette
    ports:
      - "3306:3306"

  php:
    image: sidewave/php:8.1-apache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/www/
    command: bash -c 'composer install -o && apache2ctl -D FOREGROUND'
    ports:
      - '80:80'
      - '443:443'
    networks:
      - nette

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    networks:
      - nette

networks:
  nette:
